// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-xLNF3bA2beYJ4f47-VPLbuwq6pHrmc',
    appId: '1:864993247239:web:26ae60d864be670ec86aa2',
    messagingSenderId: '864993247239',
    projectId: 'my-app-fitness-61158',
    authDomain: 'my-app-fitness-61158.firebaseapp.com',
    storageBucket: 'my-app-fitness-61158.firebasestorage.app',
    measurementId: 'G-MGFHPK5R9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9NFkP04-tuiCHQniMrOsDX7S2dJ2IFA',
    appId: '1:864993247239:android:b7eafa26f3f8b8a1c86aa2',
    messagingSenderId: '864993247239',
    projectId: 'my-app-fitness-61158',
    storageBucket: 'my-app-fitness-61158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDju5nNbxWYe0u_Kyq7i5Bm50Pb9ixDYQg',
    appId: '1:864993247239:ios:8c77e082b3046806c86aa2',
    messagingSenderId: '864993247239',
    projectId: 'my-app-fitness-61158',
    storageBucket: 'my-app-fitness-61158.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDju5nNbxWYe0u_Kyq7i5Bm50Pb9ixDYQg',
    appId: '1:864993247239:ios:8c77e082b3046806c86aa2',
    messagingSenderId: '864993247239',
    projectId: 'my-app-fitness-61158',
    storageBucket: 'my-app-fitness-61158.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6-xLNF3bA2beYJ4f47-VPLbuwq6pHrmc',
    appId: '1:864993247239:web:50f7ddca5526ecbac86aa2',
    messagingSenderId: '864993247239',
    projectId: 'my-app-fitness-61158',
    authDomain: 'my-app-fitness-61158.firebaseapp.com',
    storageBucket: 'my-app-fitness-61158.firebasestorage.app',
    measurementId: 'G-N5H70K4LMZ',
  );
}
