import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static const supportedLocales = [
    Locale('en', ''), // English
    Locale('es', ''), // Español
    Locale('fr', ''), // Français
    Locale('de', ''), // Deutsch
    Locale('zh', ''), // 中文
  ];

  Map<String, Map<String, String>> get _localizedValues => {
    'en': {
      // ... your existing English ones ...

      // ADMIN PLANS SCREEN — ENGLISH
      // ADMIN REPORTS SCREEN — ENGLISH
      'Admin Dashboard': 'Admin Dashboard',
      'Total Users': 'Total Users',
      'Active Trainers': 'Active Trainers',
      'Total Revenue': 'Total Revenue',
      'Pending Payments': 'Pending Payments',
      'Quick Actions': 'Quick Actions',
      'View All': 'View All',
      'Add Trainer': 'Add Trainer',
      'View Reports': 'View Reports',
      'Manage Users': 'Manage Users',
      'Payment Requests': 'Payment Requests',
      'Recent Activity': 'Recent Activity',
      'See All': 'See All',
      'New user registered': 'New user registered',
      'Payment received': 'Payment received',
      'Trainer approved': 'Trainer approved',
      'New review': 'New review',
      'just joined': 'just joined',
      'is now active': 'is now active',
      'min ago': 'min ago',
      'hour ago': 'hour ago',
      'hours ago': 'hours ago',
      'User Management': 'User Management',
      'Search users...': 'Search users...',
      'Status': 'Status',
      'All': 'All',
      'Active': 'Active',
      'Suspended': 'Suspended',
      'Export': 'Export',
      '📊 Export CSV started...': '📊 Export CSV started...',
      'Total Users': 'Total Users',
      'No users found': 'No users found',
      'search_off': 'search_off',
      'Delete User': 'Delete User',
      'Are you sure you want to delete': 'Are you sure you want to delete',
      'User deleted successfully': 'User deleted successfully',
      'Delete': 'Delete',
      'Cancel': 'Cancel',
      'Activate': 'Activate',
      'Suspend': 'Suspend',
      '👤 Manual user creation coming soon!': '👤 Manual user creation coming soon!',
      '🔄 Users refreshed!': '🔄 Users refreshed!',
      'has been suspended': 'has been suspended',
      'has been activated': 'has been activated',
      'Manage Trainers': 'Manage Trainers',
      'Search trainers...': 'Search trainers...',
      'Status': 'Status',
      'All': 'All',
      'Pending': 'Pending',
      'Approved': 'Approved',
      'Rejected': 'Rejected',
      'Invite': 'Invite',
      '📧 Bulk invite sent to 15 trainers!': '📧 Bulk invite sent to 15 trainers!',
      'Total Trainers': 'Total Trainers',
      'Pending Approval': 'Pending Approval',
      'Active Clients': 'Active Clients',
      'No trainers found': 'No trainers found',
      'people_outline': 'people_outline',
      'Delete Trainer': 'Delete Trainer',
      'Are you sure you want to delete': 'Are you sure you want to delete',
      'Trainer deleted': 'Trainer deleted',
      'Delete': 'Delete',
      'Close': 'Close',
      'View Analytics': 'View Analytics',
      'Viewing': 'Viewing',
      'Specialty': 'Specialty',
      'approved!': 'approved!',
      'rejected!': 'rejected!',
      'Add Trainer': 'Add Trainer',
      '📧 Trainer invite sent!': '📧 Trainer invite sent!',
      "Account Settings": "Account Settings",
      "Edit Profile": "Edit Profile",
      "Change Password": "Change Password",
      "Notification Preferences": "Notification Preferences",
      "Notifications": "Notifications",
      "enabled": "enabled",
      "disabled": "disabled",
      "System Settings": "System Settings",
      "App Theme": "App Theme",
      "Default Units": "Default Units",
      "Language": "Language",
      "Done": "Done",
      "Cancel": "Cancel",
      "Coming soon!": "Coming soon!",
      "No new notifications": "No new notifications",
      "Logout": "Logout",
      "Are you sure you want to logout?": "Are you sure you want to logout?",
      "Reports & Analytics": "Reports & Analytics",
      "reportExportedPdf": "Report exported to PDF!",
      "Total Revenue": "Total Revenue",
      "Active Members": "Active Members",
      "New Signups": "New Signups",
      "Churn Rate": "Churn Rate",
      "Revenue Growth This Week": "Revenue Growth This Week",
      "Revenue Growth": "Revenue Growth",
      "Export Full Report": "Export Full Report",
      "Report exported successfully! Check your email.": "Report exported successfully! Check your email.",
      "Detailed": "Detailed",
      "Detailed analytics coming soon!": "Detailed analytics coming soon!",

      "Mon": "Mon",
      "Tue": "Tue",
      "Wed": "Wed",
      "Thu": "Thu",
      "Fri": "Fri",
      "Sat": "Sat",
      "Sun": "Sun",

      "Plan Distribution": "Plan Distribution",
      "Premium Plan": "Premium Plan",
      "Basic Plan": "Basic Plan",
      "Elite Plan": "Elite Plan",

      "Recent Activity": "Recent Activity",
      "hours ago": "hours ago",
      "View All Activity": "View All Activity",
      "Showing full activity log...": "Showing full activity log...",

      "Membership Plans": "Membership Plans",
      "Active": "Active",
      "Edit Plan": "Edit Plan",
      "Delete": "Delete",
      "Users Assigned (%d)": "Users Assigned (%d)",
      "View All": "View All",
      "Joined %s": "Joined %s",
      "+ and more...": "+ and more...",
      "New Plan": "New Plan",
      "New plan creation coming soon!": "New plan creation coming soon!",
      "Edit %s": "Edit %s",
      "Edit plan details here (full form coming soon)": "Edit plan details here (full form coming soon)",
      "Cancel": "Cancel",
      "Save": "Save",
      "Delete Plan?": "Delete Plan?",
      "Remove '%s' permanently?": "Remove '%s' permanently?",
      "%s updated successfully!": "%s updated successfully!",
      "%s deleted!": "%s deleted!",
      "Showing %d users for %s": "Showing %d users for %s",

      "Premium Plan": "Premium Plan",
      "Basic Plan": "Basic Plan",
      "Elite Plan": "Elite Plan",
      "month": "month",
      "Unlimited classes": "Unlimited classes",
      "Personal trainer access": "Personal trainer access",
      "Priority chat support": "Priority chat support",
      "20 classes/month": "20 classes/month",
      "Community access": "Community access",
      "Weekly check-ins": "Weekly check-ins",
      "Everything in Premium": "Everything in Premium",
      "1-on-1 coaching": "1-on-1 coaching",
      "Custom nutrition plan": "Custom nutrition plan",
      "24/7 priority support": "24/7 priority support",
    },
    'es': {
      'Admin Dashboard': 'Panel de Administración',
      'Total Users': 'Total Usuarios',
      'Active Trainers': 'Entrenadores Activos',
      'Total Revenue': 'Ingresos Totales',
      'Pending Payments': 'Pagos Pendientes',
      'Quick Actions': 'Acciones Rápidas',
      'View All': 'Ver Todo',
      'Add Trainer': 'Agregar Entrenador',
      'View Reports': 'Ver Reportes',
      'Manage Users': 'Gestionar Usuarios',
      'Payment Requests': 'Solicitudes de Pago',
      'Recent Activity': 'Actividad Reciente',
      'See All': 'Ver Todo',
      'New user registered': 'Nuevo usuario registrado',
      'Payment received': 'Pago recibido',
      'Trainer approved': 'Entrenador aprobado',
      'New review': 'Nueva reseña',
      'just joined': 'acaba de unirse',
      'is now active': 'ahora está activo',
      'min ago': 'min atrás',
      'hour ago': 'hora atrás',
      'hours ago': 'horas atrás',
      'User Management': 'Gestión de Usuarios',
      'Search users...': 'Buscar usuarios...',
      'Status': 'Estado',
      'All': 'Todos',
      'Active': 'Activo',
      'Suspended': 'Suspendido',
      'Export': 'Exportar',
      '📊 Export CSV started...': '📊 Exportación CSV iniciada...',
      'Total Users': 'Total Usuarios',
      'No users found': 'No se encontraron usuarios',
      'search_off': 'search_off',
      'Delete User': 'Eliminar Usuario',
      'Are you sure you want to delete': '¿Estás seguro de que quieres eliminar',
      'User deleted successfully': 'Usuario eliminado exitosamente',
      'Delete': 'Eliminar',
      'Cancel': 'Cancelar',
      'Activate': 'Activar',
      'Suspend': 'Suspender',
      '👤 Manual user creation coming soon!': '👤 ¡Creación manual de usuarios próximamente!',
      '🔄 Users refreshed!': '🔄 ¡Usuarios actualizados!',
      'has been suspended': 'ha sido suspendido',
      'has been activated': 'ha sido activado',
      'Manage Trainers': 'Gestionar Entrenadores',
      'Search trainers...': 'Buscar entrenadores...',
      'Status': 'Estado',
      'All': 'Todos',
      'Pending': 'Pendiente',
      'Approved': 'Aprobado',
      'Rejected': 'Rechazado',
      'Invite': 'Invitar',
      '📧 Bulk invite sent to 15 trainers!': '📧 ¡Invitación masiva enviada a 15 entrenadores!',
      'Total Trainers': 'Total Entrenadores',
      'Pending Approval': 'Pendiente de Aprobación',
      'Active Clients': 'Clientes Activos',
      'No trainers found': 'No se encontraron entrenadores',
      'people_outline': 'people_outline',
      'Delete Trainer': 'Eliminar Entrenador',
      'Are you sure you want to delete': '¿Estás seguro de que quieres eliminar',
      'Trainer deleted': 'Entrenador eliminado',
      'Delete': 'Eliminar',
      'Close': 'Cerrar',
      'View Analytics': 'Ver Analíticas',
      'Viewing': 'Visualizando',
      'Specialty': 'Especialidad',
      'approved!': '¡aprobado!',
      'rejected!': '¡rechazado!',
      'Add Trainer': 'Agregar Entrenador',
      '📧 Trainer invite sent!': '📧 ¡Invitación de entrenador enviada!',
      "Account Settings": "Configuración de cuenta",
      "Edit Profile": "Editar perfil",
      "Change Password": "Cambiar contraseña",
      "Notification Preferences": "Preferencias de notificaciones",
      "Notifications": "Notificaciones",
      "enabled": "activadas",
      "disabled": "desactivadas",
      "System Settings": "Configuración del sistema",
      "App Theme": "Tema de la aplicación",
      "Default Units": "Unidades por defecto",
      "Language": "Idioma",
      "Done": "Hecho",
      "Cancel": "Cancelar",
      "Coming soon!": "¡Próximamente!",
      "No new notifications": "No hay nuevas notificaciones",
      "Logout": "Cerrar sesión",
      "Are you sure you want to logout?": "¿Seguro que deseas cerrar sesión?",
      "Reports & Analytics": "Informes y Análisis",
      "reportExportedPdf": "¡Informe exportado a PDF!",
      "Total Revenue": "Ingresos Totales",
      "Active Members": "Miembros Activos",
      "New Signups": "Nuevos Registros",
      "Churn Rate": "Tasa de Cancelación",
      "Revenue Growth This Week": "Crecimiento de Ingresos Esta Semana",
      "Revenue Growth": "Crecimiento de Ingresos",
      "Export Full Report": "Exportar Informe Completo",
      "Report exported successfully! Check your email.": "¡Informe exportado con éxito! Revisa tu correo.",
      "Detailed": "Detallado",
      "Detailed analytics coming soon!": "¡Análisis detallados próximamente!",

      "Mon": "Lun",
      "Tue": "Mar",
      "Wed": "Mié",
      "Thu": "Jue",
      "Fri": "Vie",
      "Sat": "Sáb",
      "Sun": "Dom",

      "Plan Distribution": "Distribución de Planes",
      "Recent Activity": "Actividad Reciente",
      "hours ago": "horas atrás",
      "View All Activity": "Ver Toda la Actividad",
      "Showing full activity log...": "Mostrando registro completo...",

      "Membership Plans": "Planes de Membresía",
      "Active": "Activo",
      "Edit Plan": "Editar Plan",
      "Delete": "Eliminar",
      "Users Assigned (%d)": "Usuarios Asignados (%d)",
      "View All": "Ver Todos",
      "Joined %s": "Se unió %s",
      "+ and more...": "+ y más...",
      "New Plan": "Nuevo Plan",
      "New plan creation coming soon!": "¡Creación de nuevo plan próximamente!",
      "Edit %s": "Editar %s",
      "Edit plan details here (full form coming soon)": "Edita los detalles del plan aquí (formulario completo próximamente)",
      "Cancel": "Cancelar",
      "Save": "Guardar",
      "Delete Plan?": "¿Eliminar Plan?",
      "Remove '%s' permanently?": "¿Eliminar '%s' permanentemente?",
      "%s updated successfully!": "¡%s actualizado con éxito!",
      "%s deleted!": "¡%s eliminado!",
      "Showing %d users for %s": "Mostrando %d usuarios para %s",

      "Premium Plan": "Plan Premium",
      "Basic Plan": "Plan Básico",
      "Elite Plan": "Plan Élite",
      "month": "mes",
      "Unlimited classes": "Clases ilimitadas",
      "Personal trainer access": "Acceso a entrenador personal",
      "Priority chat support": "Soporte por chat prioritario",
      "20 classes/month": "20 clases/mes",
      "Community access": "Acceso a la comunidad",
      "Weekly check-ins": "Check-ins semanales",
      "Everything in Premium": "Todo lo del Premium",
      "1-on-1 coaching": "Coaching 1 a 1",
      "Custom nutrition plan": "Plan de nutrición personalizado",
      "24/7 priority support": "Soporte prioritario 24/7",
    },
    'fr': {
      'Admin Dashboard': 'Tableau de Bord Admin',
      'Total Users': 'Total Utilisateurs',
      'Active Trainers': 'Entraîneurs Actifs',
      'Total Revenue': 'Revenu Total',
      'Pending Payments': 'Paiements en Attente',
      'Quick Actions': 'Actions Rapides',
      'View All': 'Voir Tout',
      'Add Trainer': 'Ajouter Entraîneur',
      'View Reports': 'Voir Rapports',
      'Manage Users': 'Gérer Utilisateurs',
      'Payment Requests': 'Demandes de Paiement',
      'Recent Activity': 'Activité Récente',
      'See All': 'Voir Tout',
      'New user registered': 'Nouvel utilisateur inscrit',
      'Payment received': 'Paiement reçu',
      'Trainer approved': 'Entraîneur approuvé',
      'New review': 'Nouvelle évaluation',
      'just joined': 'vient de rejoindre',
      'is now active': 'est maintenant actif',
      'min ago': 'min avant',
      'hour ago': '1 heure avant',
      'hours ago': 'heures avant',
      'User Management': 'Gestion des Utilisateurs',
      'Search users...': 'Rechercher des utilisateurs...',
      'Status': 'Statut',
      'All': 'Tous',
      'Active': 'Actif',
      'Suspended': 'Suspendu',
      'Export': 'Exporter',
      '📊 Export CSV started...': '📊 Exportation CSV démarrée...',
      'Total Users': 'Total Utilisateurs',
      'No users found': 'Aucun utilisateur trouvé',
      'search_off': 'search_off',
      'Delete User': 'Supprimer l\'utilisateur',
      'Are you sure you want to delete': 'Êtes-vous sûr de vouloir supprimer',
      'User deleted successfully': 'Utilisateur supprimé avec succès',
      'Delete': 'Supprimer',
      'Cancel': 'Annuler',
      'Activate': 'Activer',
      'Suspend': 'Suspendre',
      '👤 Manual user creation coming soon!': '👤 Création manuelle d\'utilisateurs bientôt disponible !',
      '🔄 Users refreshed!': '🔄 Utilisateurs actualisés !',
      'has been suspended': 'a été suspendu',
      'has been activated': 'a été activé',
      'Manage Trainers': 'Gérer les Entraîneurs',
      'Search trainers...': 'Rechercher des entraîneurs...',
      'Status': 'Statut',
      'All': 'Tous',
      'Pending': 'En attente',
      'Approved': 'Approuvé',
      'Rejected': 'Rejeté',
      'Invite': 'Inviter',
      '📧 Bulk invite sent to 15 trainers!': '📧 Invitation groupée envoyée à 15 entraîneurs !',
      'Total Trainers': 'Total Entraîneurs',
      'Pending Approval': 'En attente d\'approbation',
      'Active Clients': 'Clients Actifs',
      'No trainers found': 'Aucun entraîneur trouvé',
      'people_outline': 'people_outline',
      'Delete Trainer': 'Supprimer l\'entraîneur',
      'Are you sure you want to delete': 'Êtes-vous sûr de vouloir supprimer',
      'Trainer deleted': 'Entraîneur supprimé',
      'Delete': 'Supprimer',
      'Close': 'Fermer',
      'View Analytics': 'Voir les analyses',
      'Viewing': 'Visualisation',
      'Specialty': 'Spécialité',
      'approved!': 'approuvé !',
      'rejected!': 'rejeté !',
      'Add Trainer': 'Ajouter un Entraîneur',
      '📧 Trainer invite sent!': '📧 Invitation d\'entraîneur envoyée !',
      "Account Settings": "Paramètres du compte",
      "Edit Profile": "Modifier le profil",
      "Change Password": "Changer le mot de passe",
      "Notification Preferences": "Préférences de notification",
      "Notifications": "Notifications",
      "enabled": "activées",
      "disabled": "désactivées",
      "System Settings": "Paramètres système",
      "App Theme": "Thème de l'application",
      "Default Units": "Unités par défaut",
      "Language": "Langue",
      "Done": "Terminé",
      "Cancel": "Annuler",
      "Coming soon!": "Bientôt disponible !",
      "No new notifications": "Aucune nouvelle notification",
      "Logout": "Se déconnecter",
      "Are you sure you want to logout?": "Êtes-vous sûr de vouloir vous déconnecter ?",

      "Reports & Analytics": "Rapports et Analyses",
      "reportExportedPdf": "Rapport exporté en PDF !",
      "Total Revenue": "Revenu Total",
      "Active Members": "Membres Actifs",
      "New Signups": "Nouvelles Inscriptions",
      "Churn Rate": "Taux d’Abandon",
      "Revenue Growth This Week": "Croissance des Revenus Cette Semaine",
      "Revenue Growth": "Croissance des Revenus",
      "Export Full Report": "Exporter le Rapport Complet",
      "Report exported successfully! Check your email.": "Rapport exporté avec succès ! Vérifiez votre e-mail.",
      "Detailed": "Détaillé",
      "Detailed analytics coming soon!": "Analyses détaillées bientôt disponibles !",

      "Mon": "Lun",
      "Tue": "Mar",
      "Wed": "Mer",
      "Thu": "Jeu",
      "Fri": "Ven",
      "Sat": "Sam",
      "Sun": "Dim",

      "Plan Distribution": "Répartition des Formules",
      "Recent Activity": "Activité Récente",
      "hours ago": "heures avant",
      "View All Activity": "Voir toute l’activité",
      "Showing full activity log...": "Affichage du journal complet...",

      "Membership Plans": "Formules d'abonnement",
      "Active": "Actif",
      "Edit Plan": "Modifier le plan",
      "Delete": "Supprimer",
      "Users Assigned (%d)": "Utilisateurs assignés (%d)",
      "View All": "Voir tout",
      "Joined %s": "Inscrit le %s",
      "+ and more...": "+ et plus...",
      "New Plan": "Nouveau plan",
      "New plan creation coming soon!": "Création de nouveau plan bientôt disponible !",
      "Edit %s": "Modifier %s",
      "Edit plan details here (full form coming soon)": "Modifiez les détails ici (formulaire complet bientôt)",
      "Cancel": "Annuler",
      "Save": "Sauvegarder",
      "Delete Plan?": "Supprimer le plan ?",
      "Remove '%s' permanently?": "Supprimer définitivement '%s' ?",
      "%s updated successfully!": "%s mis à jour avec succès !",
      "%s deleted!": "%s supprimé !",
      "Showing %d users for %s": "Affichage de %d utilisateurs pour %s",

      "Premium Plan": "Plan Premium",
      "Basic Plan": "Plan Basique",
      "Elite Plan": "Plan Élite",
      "month": "mois",
      "Unlimited classes": "Cours illimités",
      "Personal trainer access": "Accès coach personnel",
      "Priority chat support": "Support chat prioritaire",
      "20 classes/month": "20 cours/mois",
      "Community access": "Accès communauté",
      "Weekly check-ins": "Check-ins hebdomadaires",
      "Everything in Premium": "Tout du Premium",
      "1-on-1 coaching": "Coaching individuel",
      "Custom nutrition plan": "Plan nutrition personnalisé",
      "24/7 priority support": "Support prioritaire 24/7",
    },
    'de': {
      'Admin Dashboard': 'Admin-Dashboard',
      'Total Users': 'Gesamt Benutzer',
      'Active Trainers': 'Aktive Trainer',
      'Total Revenue': 'Gesamtumsatz',
      'Pending Payments': 'Ausstehende Zahlungen',
      'Quick Actions': 'Schnelle Aktionen',
      'View All': 'Alle Anzeigen',
      'Add Trainer': 'Trainer Hinzufügen',
      'View Reports': 'Berichte Anzeigen',
      'Manage Users': 'Benutzer Verwalten',
      'Payment Requests': 'Zahlungsanfragen',
      'Recent Activity': 'Letzte Aktivitäten',
      'See All': 'Alle Anzeigen',
      'New user registered': 'Neuer Benutzer registriert',
      'Payment received': 'Zahlung erhalten',
      'Trainer approved': 'Trainer genehmigt',
      'New review': 'Neue Bewertung',
      'just joined': 'gerade beigetreten',
      'is now active': 'ist jetzt aktiv',
      'min ago': 'Min. zuvor',
      'hour ago': '1 Std. zuvor',
      'hours ago': 'Std. zuvor',
      'User Management': 'Benutzerverwaltung',
      'Search users...': 'Benutzer suchen...',
      'Status': 'Status',
      'All': 'Alle',
      'Active': 'Aktiv',
      'Suspended': 'Gesperrt',
      'Export': 'Exportieren',
      '📊 Export CSV started...': '📊 CSV-Export gestartet...',
      'Total Users': 'Gesamt Benutzer',
      'No users found': 'Keine Benutzer gefunden',
      'search_off': 'search_off',
      'Delete User': 'Benutzer löschen',
      'Are you sure you want to delete': 'Sind Sie sicher, dass Sie löschen möchten',
      'User deleted successfully': 'Benutzer erfolgreich gelöscht',
      'Delete': 'Löschen',
      'Cancel': 'Abbrechen',
      'Activate': 'Aktivieren',
      'Suspend': 'Sperren',
      '👤 Manual user creation coming soon!': '👤 Manuelle Benutzererstellung kommt bald!',
      '🔄 Users refreshed!': '🔄 Benutzer aktualisiert!',
      'has been suspended': 'wurde gesperrt',
      'has been activated': 'wurde aktiviert',
      'Manage Trainers': 'Trainer verwalten',
      'Search trainers...': 'Trainer suchen...',
      'Status': 'Status',
      'All': 'Alle',
      'Pending': 'Ausstehend',
      'Approved': 'Genehmigt',
      'Rejected': 'Abgelehnt',
      'Invite': 'Einladen',
      '📧 Bulk invite sent to 15 trainers!': '📧 Masseneinladung an 15 Trainer gesendet!',
      'Total Trainers': 'Gesamt Trainer',
      'Pending Approval': 'Warten auf Genehmigung',
      'Active Clients': 'Aktive Kunden',
      'No trainers found': 'Keine Trainer gefunden',
      'people_outline': 'people_outline',
      'Delete Trainer': 'Trainer löschen',
      'Are you sure you want to delete': 'Sind Sie sicher, dass Sie löschen möchten',
      'Trainer deleted': 'Trainer gelöscht',
      'Delete': 'Löschen',
      'Close': 'Schließen',
      'View Analytics': 'Analysen anzeigen',
      'Viewing': 'Anzeige',
      'Specialty': 'Spezialisierung',
      'approved!': 'genehmigt!',
      'rejected!': 'abgelehnt!',
      'Add Trainer': 'Trainer hinzufügen',
      '📧 Trainer invite sent!': '📧 Trainereinladung gesendet!',
      "Account Settings": "Kontoeinstellungen",
      "Edit Profile": "Profil bearbeiten",
      "Change Password": "Passwort ändern",
      "Notification Preferences": "Benachrichtigungseinstellungen",
      "Notifications": "Benachrichtigungen",
      "enabled": "aktiviert",
      "disabled": "deaktiviert",
      "System Settings": "Systemeinstellungen",
      "App Theme": "App-Design",
      "Default Units": "Standardeinheiten",
      "Language": "Sprache",
      "Done": "Fertig",
      "Cancel": "Abbrechen",
      "Coming soon!": "Kommt bald!",
      "No new notifications": "Keine neuen Benachrichtigungen",
      "Logout": "Abmelden",
      "Are you sure you want to logout?": "Möchten Sie sich wirklich abmelden?",

      "Reports & Analytics": "Berichte & Analysen",
      "reportExportedPdf": "Bericht als PDF exportiert!",
      "Total Revenue": "Gesamtumsatz",
      "Active Members": "Aktive Mitglieder",
      "New Signups": "Neue Anmeldungen",
      "Churn Rate": "Abwanderungsrate",
      "Revenue Growth This Week": "Umsatzwachstum Diese Woche",
      "Revenue Growth": "Umsatzwachstum",
      "Export Full Report": "Vollständigen Bericht exportieren",
      "Report exported successfully! Check your email.": "Bericht erfolgreich exportiert! Prüfen Sie Ihre E-Mail.",
      "Detailed": "Detailliert",
      "Detailed analytics coming soon!": "Detaillierte Analysen folgen bald!",

      "Mon": "Mo",
      "Tue": "Di",
      "Wed": "Mi",
      "Thu": "Do",
      "Fri": "Fr",
      "Sat": "Sa",
      "Sun": "So",

      "Plan Distribution": "Planverteilung",
      "Recent Activity": "Letzte Aktivitäten",
      "hours ago": "Stunden zuvor",
      "View All Activity": "Alle Aktivitäten anzeigen",
      "Showing full activity log...": "Vollständiges Aktivitätsprotokoll anzeigen...",

      "Membership Plans": "Mitgliedschaftspläne",
      "Active": "Aktiv",
      "Edit Plan": "Plan bearbeiten",
      "Delete": "Löschen",
      "Users Assigned (%d)": "Zugewiesene Nutzer (%d)",
      "View All": "Alle anzeigen",
      "Joined %s": "Beigetreten am %s",
      "+ and more...": "+ und mehr...",
      "New Plan": "Neuer Plan",
      "New plan creation coming soon!": "Neuer Plan kommt bald!",
      "Edit %s": "%s bearbeiten",
      "Edit plan details here (full form coming soon)": "Details hier bearbeiten (vollständiges Formular folgt)",
      "Cancel": "Abbrechen",
      "Save": "Speichern",
      "Delete Plan?": "Plan löschen?",
      "Remove '%s' permanently?": "'%s' dauerhaft entfernen?",
      "%s updated successfully!": "%s erfolgreich aktualisiert!",
      "%s deleted!": "%s gelöscht!",
      "Showing %d users for %s": "Zeige %d Nutzer für %s",

      "Premium Plan": "Premium-Plan",
      "Basic Plan": "Basis-Plan",
      "Elite Plan": "Elite-Plan",
      "month": "Monat",
      "Unlimited classes": "Unbegrenzte Kurse",
      "Personal trainer access": "Persönlicher Trainer-Zugang",
      "Priority chat support": "Priorisierter Chat-Support",
      "20 classes/month": "20 Kurse/Monat",
      "Community access": "Community-Zugang",
      "Weekly check-ins": "Wöchentliche Check-ins",
      "Everything in Premium": "Alles aus Premium",
      "1-on-1 coaching": "1:1 Coaching",
      "Custom nutrition plan": "Individueller Ernährungsplan",
      "24/7 priority support": "24/7 Prioritätssupport",
    },
    'zh': {
      'Admin Dashboard': '管理面板',
      'Total Users': '总用户数',
      'Active Trainers': '活跃教练',
      'Total Revenue': '总收入',
      'Pending Payments': '待付款项',
      'Quick Actions': '快速操作',
      'View All': '查看全部',
      'Add Trainer': '添加教练',
      'View Reports': '查看报告',
      'Manage Users': '管理用户',
      'Payment Requests': '付款请求',
      'Recent Activity': '最近活动',
      'See All': '查看全部',
      'New user registered': '新用户注册',
      'Payment received': '已收到付款',
      'Trainer approved': '教练已批准',
      'New review': '新评价',
      'just joined': '刚刚加入',
      'is now active': '现在已激活',
      'min ago': '分钟前',
      'hour ago': '1小时前',
      'hours ago': '小时前',
      'User Management': '用户管理',
      'Search users...': '搜索用户...',
      'Status': '状态',
      'All': '全部',
      'Active': '活跃',
      'Suspended': '已暂停',
      'Export': '导出',
      '📊 Export CSV started...': '📊 CSV 导出已开始...',
      'Total Users': '总用户数',
      'No users found': '未找到用户',
      'search_off': 'search_off',
      'Delete User': '删除用户',
      'Are you sure you want to delete': '确定要删除吗',
      'User deleted successfully': '用户删除成功',
      'Delete': '删除',
      'Cancel': '取消',
      'Activate': '激活',
      'Suspend': '暂停',
      '👤 Manual user creation coming soon!': '👤 手动创建用户功能即将推出！',
      '🔄 Users refreshed!': '🔄 用户已刷新！',
      'has been suspended': '已被暂停',
      'has been activated': '已被激活',
      'Manage Trainers': '管理教练',
      'Search trainers...': '搜索教练...',
      'Status': '状态',
      'All': '全部',
      'Pending': '待审核',
      'Approved': '已批准',
      'Rejected': '已拒绝',
      'Invite': '邀请',
      '📧 Bulk invite sent to 15 trainers!': '📧 已向15名教练发送批量邀请！',
      'Total Trainers': '总教练数',
      'Pending Approval': '待批准',
      'Active Clients': '活跃客户',
      'No trainers found': '未找到教练',
      'people_outline': 'people_outline',
      'Delete Trainer': '删除教练',
      'Are you sure you want to delete': '确定要删除吗',
      'Trainer deleted': '教练已删除',
      'Delete': '删除',
      'Close': '关闭',
      'View Analytics': '查看分析',
      'Viewing': '查看中',
      'Specialty': '专长',
      'approved!': '已批准！',
      'rejected!': '已拒绝！',
      'Add Trainer': '添加教练',
      '📧 Trainer invite sent!': '📧 教练邀请已发送！',
      "Account Settings": "账户设置",
      "Edit Profile": "编辑资料",
      "Change Password": "更改密码",
      "Notification Preferences": "通知偏好",
      "Notifications": "通知",
      "enabled": "已启用",
      "disabled": "已禁用",
      "System Settings": "系统设置",
      "App Theme": "应用主题",
      "Default Units": "默认单位",
      "Language": "语言",
      "Done": "完成",
      "Cancel": "取消",
      "Coming soon!": "即将推出！",
      "No new notifications": "没有新的通知",
      "Logout": "登出",
      "Are you sure you want to logout?": "确定要登出吗？",

      "Reports & Analytics": "报告与分析",
      "reportExportedPdf": "已导出 PDF 报告！",
      "Total Revenue": "总收入",
      "Active Members": "活跃会员",
      "New Signups": "新注册",
      "Churn Rate": "流失率",
      "Revenue Growth This Week": "本周收入增长",
      "Revenue Growth": "收入增长",
      "Export Full Report": "导出完整报告",
      "Report exported successfully! Check your email.": "报告已成功导出！请检查您的邮箱。",
      "Detailed": "详细",
      "Detailed analytics coming soon!": "详细分析即将推出！",

      "Mon": "周一",
      "Tue": "周二",
      "Wed": "周三",
      "Thu": "周四",
      "Fri": "周五",
      "Sat": "周六",
      "Sun": "周日",

      "Plan Distribution": "方案分布",
      "Recent Activity": "最近活动",
      "hours ago": "小时前",
      "View All Activity": "查看所有活动",
      "Showing full activity log...": "正在显示完整活动记录...",

      "Membership Plans": "会员方案",
      "Active": "启用中",
      "Edit Plan": "编辑方案",
      "Delete": "删除",
      "Users Assigned (%d)": "已分配用户 (%d)",
      "View All": "查看全部",
      "Joined %s": "加入于 %s",
      "+ and more...": "+ 还有更多...",
      "New Plan": "新增方案",
      "New plan creation coming soon!": "新方案创建功能即将推出！",
      "Edit %s": "编辑 %s",
      "Edit plan details here (full form coming soon)": "在此编辑方案详情（完整表单即将推出）",
      "Cancel": "取消",
      "Save": "保存",
      "Delete Plan?": "删除方案？",
      "Remove '%s' permanently?": "永久移除 '%s'？",
      "%s updated successfully!": "%s 更新成功！",
      "%s deleted!": "%s 已删除！",
      "Showing %d users for %s": "正在显示 %d 位用户：%s",

      "Premium Plan": "高级方案",
      "Basic Plan": "基础方案",
      "Elite Plan": "精英方案",
      "month": "月",
      "Unlimited classes": "无限课程",
      "Personal trainer access": "专属教练服务",
      "Priority chat support": "优先聊天支持",
      "20 classes/month": "每月20节课",
      "Community access": "社区访问权限",
      "Weekly check-ins": "每周打卡",
      "Everything in Premium": "包含高级方案全部内容",
      "1-on-1 coaching": "一对一指导",
      "Custom nutrition plan": "定制营养计划",
      "24/7 priority support": "24/7 优先支持",
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.contains(locale);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => true;
}